/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author louis
 */
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;

public class Login extends javax.swing.JFrame {
    private Statement stmt;
    boolean passwordHide = true;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            JOptionPane.showMessageDialog(null, "Driver Loaded");

            String url = "jdbc:ucanaccess://C:\\Users\\louis\\Desktop\\UCI_Java_Project.accdb";

            Connection connection = DriverManager.getConnection(url);
            JOptionPane.showMessageDialog(null, "Database Connected");

            stmt = connection.createStatement();
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Error" + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSignIn = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        txtStudentNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnShowHidePassword = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Student number");

        jLabel2.setText("Password");

        btnSignIn.setText("Sign-in");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        btnSignUp.setText("Sign-up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        txtStudentNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNumberActionPerformed(evt);
            }
        });
        txtStudentNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStudentNumberKeyTyped(evt);
            }
        });

        jLabel3.setText("Project Java");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        btnShowHidePassword.setText("Show/Hide password");
        btnShowHidePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowHidePasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addComponent(btnSignIn))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(57, 57, 57)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnSignUp)
                                        .addComponent(txtStudentNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                        .addComponent(txtPassword))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnShowHidePassword)
                                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3)
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(txtStudentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSignIn)
                                        .addComponent(btnSignUp)
                                        .addComponent(btnShowHidePassword))
                                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>


    private void txtStudentNumberActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void btnShowHidePasswordActionPerformed(java.awt.event.ActionEvent evt) {
        if (passwordHide){
            txtPassword.setEchoChar((char)0);
            passwordHide = false;
        } else {
            txtPassword.setEchoChar('*');
            passwordHide = true;
        }

    }

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {
        txtPassword.setEchoChar('*');
    }

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {
        String studentNumber = txtStudentNumber.getText();
        char[] passwordChar = txtPassword.getPassword();
        String password;

        StringBuilder sb = new StringBuilder();

        for (char ch : passwordChar){
            sb.append(ch);
        }

        password = sb.toString();

        try {
            System.out.println(1);
            String QueryString = "SELECT * FROM Students WHERE Student_ID='" + studentNumber + "'and Password='" + password + "'";

            ResultSet rset = stmt.executeQuery(QueryString);

            if(rset.next() && studentNumber.equals(studentNumber) && password.equals(password)){
                String id = rset.getString(1);
                String passwordRset = rset.getString(2);
                JOptionPane.showMessageDialog(null, "Welcome students nb : "+id);
                Menu m = new Menu();
                m.setVisible(true);
                this.setVisible(false);

            }else{
                JOptionPane.showMessageDialog(null, "Wrong user or password");
                txtStudentNumber.setText("");
                txtPassword.setText("");
                txtStudentNumber.requestFocus();
            }
            rset.close();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Wrong user or password");
        }
    }

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {
        SignUp signUp = new SignUp();
        signUp.setVisible(true);
        this.setVisible(false);
    }

    private void txtStudentNumberKeyTyped(java.awt.event.KeyEvent evt) {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnShowHidePassword;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtStudentNumber;
    // End of variables declaration
}
